base: &base
  adapter: postgresql
  encoding: utf8
  username: zutha
  password: zutha
  host: 127.0.0.1
  pool: 5

development:
  <<: *base
  database: zutha_development

test: &TEST
  <<: *base
  database: zutha_test

# pg_restore --verbose --clean --no-acl --no-owner -h 127.0.0.1 -U zutha -d zutha_development b001.dump